void line(){
	iSetColor(239,228,176);
	if(level==0){
		//if(word_level_0[word1.easy][0]=='B'&&word_level_0[word1.easy][1]=='A'&&word_level_0[word1.easy][2]=='T'){
		if(word_level_0[WordRandom[Index]][0]=='T'&&word_level_0[WordRandom[Index]][1]=='A'&&word_level_0[WordRandom[Index]][2]=='B'){
			if(arr[0]=='B'&&arr[1]=='A'||arr[1]=='B'&&arr[2]=='A'||arr[0]=='A'&&arr[1]=='B'||arr[1]=='A'&&arr[2]=='B'){
				iFilledCircle(position_x.tab.a+(WidthOfImage/2),position_y.tab.a+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tab.b+(WidthOfImage/2),position_y.tab.b+(WidthOfImage/2),3,6);
				iLine(position_x.tab.a+(WidthOfImage/2),position_y.tab.a+(HeightOfImage/2),position_x.tab.b+(WidthOfImage/2),position_y.tab.b+(HeightOfImage/2));
			}
			if(arr[0]=='T'&&arr[1]=='A'||arr[1]=='T'&&arr[2]=='A'||arr[0]=='A'&&arr[1]=='T'||arr[1]=='A'&&arr[2]=='T'){
				iFilledCircle(position_x.tab.a+(WidthOfImage/2),position_y.tab.a+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tab.t+(WidthOfImage/2),position_y.tab.t+(WidthOfImage/2),3,6);
				iLine(position_x.tab.a+(WidthOfImage/2),position_y.tab.a+(HeightOfImage/2),position_x.tab.t+(WidthOfImage/2),position_y.tab.t+(HeightOfImage/2));
			}
			if(arr[0]=='B'&&arr[1]=='T'||arr[1]=='B'&&arr[2]=='T'||arr[0]=='T'&&arr[1]=='B'||arr[1]=='T'&&arr[2]=='B'){
				iFilledCircle(position_x.tab.t+(WidthOfImage/2),position_y.tab.t+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tab.b+(WidthOfImage/2),position_y.tab.b+(WidthOfImage/2),3,6);
				iLine(position_x.tab.t+(WidthOfImage/2),position_y.tab.t+(HeightOfImage/2),position_x.tab.b+(WidthOfImage/2),position_y.tab.b+(HeightOfImage/2));
			}
		}
		if(word_level_0[WordRandom[Index]][0]=='R'&&word_level_0[WordRandom[Index]][1]=='O'&&word_level_0[WordRandom[Index]][2]=='B'){
			if(arr[0]=='B'&&arr[1]=='O'||arr[1]=='B'&&arr[2]=='O'||arr[0]=='O'&&arr[1]=='B'||arr[1]=='O'&&arr[2]=='B'){
				iFilledCircle(position_x.rob.o+(WidthOfImage/2),position_y.rob.o+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.rob.b+(WidthOfImage/2),position_y.rob.b+(WidthOfImage/2),3,6);
				iLine(position_x.rob.o+(WidthOfImage/2),position_y.rob.o+(HeightOfImage/2),position_x.rob.b+(WidthOfImage/2),position_y.rob.b+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='O'||arr[1]=='R'&&arr[2]=='O'||arr[0]=='O'&&arr[1]=='R'||arr[1]=='O'&&arr[2]=='R'){
				iFilledCircle(position_x.rob.o+(WidthOfImage/2),position_y.rob.o+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.rob.r+(WidthOfImage/2),position_y.rob.r+(WidthOfImage/2),3,6);
				iLine(position_x.rob.o+(WidthOfImage/2),position_y.rob.o+(HeightOfImage/2),position_x.rob.r+(WidthOfImage/2),position_y.rob.r+(HeightOfImage/2));
			}
			if(arr[0]=='B'&&arr[1]=='R'||arr[1]=='B'&&arr[2]=='R'||arr[0]=='R'&&arr[1]=='B'||arr[1]=='R'&&arr[2]=='B'){
				iFilledCircle(position_x.rob.r+(WidthOfImage/2),position_y.rob.r+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.rob.b+(WidthOfImage/2),position_y.rob.b+(WidthOfImage/2),3,6);
				iLine(position_x.rob.r+(WidthOfImage/2),position_y.rob.r+(HeightOfImage/2),position_x.rob.b+(WidthOfImage/2),position_y.rob.b+(HeightOfImage/2));
			}
		}
		if(word_level_0[WordRandom[Index]][0]=='M'&&word_level_0[WordRandom[Index]][1]=='A'&&word_level_0[WordRandom[Index]][2]=='D'){
			if(arr[0]=='D'&&arr[1]=='A'||arr[1]=='D'&&arr[2]=='A'||arr[0]=='A'&&arr[1]=='D'||arr[1]=='A'&&arr[2]=='D'){
				iFilledCircle(position_x.mad.a+(WidthOfImage/2),position_y.mad.a+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.mad.d+(WidthOfImage/2),position_y.mad.d+(WidthOfImage/2),3,6);
				iLine(position_x.mad.a+(WidthOfImage/2),position_y.mad.a+(HeightOfImage/2),position_x.mad.d+(WidthOfImage/2),position_y.mad.d+(HeightOfImage/2));
			}
			if(arr[0]=='M'&&arr[1]=='A'||arr[1]=='M'&&arr[2]=='A'||arr[0]=='A'&&arr[1]=='M'||arr[1]=='A'&&arr[2]=='M'){
				iFilledCircle(position_x.mad.a+(WidthOfImage/2),position_y.mad.a+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.mad.m+(WidthOfImage/2),position_y.mad.m+(WidthOfImage/2),3,6);
				iLine(position_x.mad.a+(WidthOfImage/2),position_y.mad.a+(HeightOfImage/2),position_x.mad.m+(WidthOfImage/2),position_y.mad.m+(HeightOfImage/2));
			}
			if(arr[0]=='D'&&arr[1]=='M'||arr[1]=='D'&&arr[2]=='M'||arr[0]=='M'&&arr[1]=='D'||arr[1]=='M'&&arr[2]=='D'){
				iFilledCircle(position_x.mad.m+(WidthOfImage/2),position_y.mad.m+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.mad.d+(WidthOfImage/2),position_y.mad.d+(WidthOfImage/2),3,6);
				iLine(position_x.mad.m+(WidthOfImage/2),position_y.mad.m+(HeightOfImage/2),position_x.mad.d+(WidthOfImage/2),position_y.mad.d+(HeightOfImage/2));
			}
		}
		if(word_level_0[WordRandom[Index]][0]=='T'&&word_level_0[WordRandom[Index]][1]=='I'&&word_level_0[WordRandom[Index]][2]=='P'){
			if(arr[0]=='P'&&arr[1]=='I'||arr[1]=='P'&&arr[2]=='I'||arr[0]=='I'&&arr[1]=='P'||arr[1]=='I'&&arr[2]=='P'){
				iFilledCircle(position_x.tip.i+(WidthOfImage/2),position_y.tip.i+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tip.p+(WidthOfImage/2),position_y.tip.p+(WidthOfImage/2),3,6);
				iLine(position_x.tip.i+(WidthOfImage/2),position_y.tip.i+(HeightOfImage/2),position_x.tip.p+(WidthOfImage/2),position_y.tip.p+(HeightOfImage/2));
			}
			if(arr[0]=='T'&&arr[1]=='I'||arr[1]=='T'&&arr[2]=='I'||arr[0]=='I'&&arr[1]=='T'||arr[1]=='I'&&arr[2]=='T'){
				iFilledCircle(position_x.tip.i+(WidthOfImage/2),position_y.tip.i+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tip.t+(WidthOfImage/2),position_y.tip.t+(WidthOfImage/2),3,6);
				iLine(position_x.tip.i+(WidthOfImage/2),position_y.tip.i+(HeightOfImage/2),position_x.tip.t+(WidthOfImage/2),position_y.tip.t+(HeightOfImage/2));
			}
			if(arr[0]=='P'&&arr[1]=='T'||arr[1]=='P'&&arr[2]=='T'||arr[0]=='T'&&arr[1]=='P'||arr[1]=='T'&&arr[2]=='P'){
				iFilledCircle(position_x.tip.t+(WidthOfImage/2),position_y.tip.t+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tip.p+(WidthOfImage/2),position_y.tip.p+(WidthOfImage/2),3,6);
				iLine(position_x.tip.t+(WidthOfImage/2),position_y.tip.t+(HeightOfImage/2),position_x.tip.p+(WidthOfImage/2),position_y.tip.p+(HeightOfImage/2));
			}
		}
		if(word_level_0[WordRandom[Index]][0]=='T'&&word_level_0[WordRandom[Index]][1]=='A'&&word_level_0[WordRandom[Index]][2]=='P'){
			if(arr[0]=='P'&&arr[1]=='A'||arr[1]=='P'&&arr[2]=='A'||arr[0]=='A'&&arr[1]=='P'||arr[1]=='A'&&arr[2]=='P'){
				iFilledCircle(position_x.tap.a+(WidthOfImage/2),position_y.tap.a+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tap.p+(WidthOfImage/2),position_y.tap.p+(WidthOfImage/2),3,6);
				iLine(position_x.tap.a+(WidthOfImage/2),position_y.tap.a+(HeightOfImage/2),position_x.tap.p+(WidthOfImage/2),position_y.tap.p+(HeightOfImage/2));
			}
			if(arr[0]=='T'&&arr[1]=='A'||arr[1]=='T'&&arr[2]=='A'||arr[0]=='A'&&arr[1]=='T'||arr[1]=='A'&&arr[2]=='T'){
				iFilledCircle(position_x.tap.a+(WidthOfImage/2),position_y.tap.a+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tap.t+(WidthOfImage/2),position_y.tap.t+(WidthOfImage/2),3,6);
				iLine(position_x.tap.a+(WidthOfImage/2),position_y.tap.a+(HeightOfImage/2),position_x.tap.t+(WidthOfImage/2),position_y.tap.t+(HeightOfImage/2));
			}
			if(arr[0]=='P'&&arr[1]=='T'||arr[1]=='P'&&arr[2]=='T'||arr[0]=='T'&&arr[1]=='P'||arr[1]=='T'&&arr[2]=='P'){
				iFilledCircle(position_x.tap.t+(WidthOfImage/2),position_y.tap.t+(WidthOfImage/2),3,6);
				iFilledCircle(position_x.tap.p+(WidthOfImage/2),position_y.tap.p+(WidthOfImage/2),3,6);
				iLine(position_x.tap.t+(WidthOfImage/2),position_y.tap.t+(HeightOfImage/2),position_x.tap.p+(WidthOfImage/2),position_y.tap.p+(HeightOfImage/2));
			}
		}
	}
	if(level==1){
		if(word_level_1[WordRandom[Index]][0]=='W'&&word_level_1[WordRandom[Index]][1]=='O'&&word_level_1[WordRandom[Index]][2]=='R'&&word_level_1[WordRandom[Index]][3]=='D'){
			if(arr[0]=='W'&&arr[1]=='O'||arr[1]=='W'&&arr[2]=='O'||arr[2]=='W'&&arr[3]=='O'||arr[0]=='O'&&arr[1]=='W'||arr[1]=='O'&&arr[2]=='W'||arr[2]=='O'&&arr[3]=='W'){
					iFilledCircle(position_x.word.w+(WidthOfImage/2),position_y.word.w+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.word.o+(WidthOfImage/2),position_y.word.o+(WidthOfImage/2),3,6);
					iLine(position_x.word.w+(WidthOfImage/2),position_y.word.w+(HeightOfImage/2),position_x.word.o+(WidthOfImage/2),position_y.word.o+(HeightOfImage/2));
			}
			if(arr[0]=='W'&&arr[1]=='D'||arr[1]=='W'&&arr[2]=='D'||arr[2]=='W'&&arr[3]=='D'||arr[0]=='D'&&arr[1]=='W'||arr[1]=='D'&&arr[2]=='W'||arr[2]=='D'&&arr[3]=='W'){
					iFilledCircle(position_x.word.w+(WidthOfImage/2),position_y.word.w+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.word.d+(WidthOfImage/2),position_y.word.d+(WidthOfImage/2),3,6);
					iLine(position_x.word.w+(WidthOfImage/2),position_y.word.w+(HeightOfImage/2),position_x.word.d+(WidthOfImage/2),position_y.word.d+(HeightOfImage/2));
			}
			if(arr[0]=='W'&&arr[1]=='R'||arr[1]=='W'&&arr[2]=='R'||arr[2]=='W'&&arr[3]=='R'||arr[0]=='R'&&arr[1]=='W'||arr[1]=='R'&&arr[2]=='W'||arr[2]=='R'&&arr[3]=='W'){
					iFilledCircle(position_x.word.w+(WidthOfImage/2),position_y.word.w+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.word.r+(WidthOfImage/2),position_y.word.r+(WidthOfImage/2),3,6);
					iLine(position_x.word.w+(WidthOfImage/2),position_y.word.w+(HeightOfImage/2),position_x.word.r+(WidthOfImage/2),position_y.word.r+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='O'||arr[1]=='R'&&arr[2]=='O'||arr[2]=='R'&&arr[3]=='O'||arr[0]=='O'&&arr[1]=='R'||arr[1]=='O'&&arr[2]=='R'||arr[2]=='O'&&arr[3]=='R'){
					iFilledCircle(position_x.word.r+(WidthOfImage/2),position_y.word.r+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.word.o+(WidthOfImage/2),position_y.word.o+(WidthOfImage/2),3,6);
					iLine(position_x.word.r+(WidthOfImage/2),position_y.word.r+(HeightOfImage/2),position_x.word.o+(WidthOfImage/2),position_y.word.o+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='D'||arr[1]=='R'&&arr[2]=='D'||arr[2]=='R'&&arr[3]=='D'||arr[0]=='D'&&arr[1]=='R'||arr[1]=='D'&&arr[2]=='R'||arr[2]=='D'&&arr[3]=='R'){
					iFilledCircle(position_x.word.r+(WidthOfImage/2),position_y.word.r+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.word.d+(WidthOfImage/2),position_y.word.d+(WidthOfImage/2),3,6);
					iLine(position_x.word.r+(WidthOfImage/2),position_y.word.r+(HeightOfImage/2),position_x.word.d+(WidthOfImage/2),position_y.word.d+(HeightOfImage/2));
			}
			if(arr[0]=='D'&&arr[1]=='O'||arr[1]=='D'&&arr[2]=='O'||arr[2]=='D'&&arr[3]=='O'||arr[0]=='O'&&arr[1]=='D'||arr[1]=='O'&&arr[2]=='D'||arr[2]=='O'&&arr[3]=='D'){
					iFilledCircle(position_x.word.d+(WidthOfImage/2),position_y.word.d+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.word.o+(WidthOfImage/2),position_y.word.o+(WidthOfImage/2),3,6);
					iLine(position_x.word.d+(WidthOfImage/2),position_y.word.d+(HeightOfImage/2),position_x.word.o+(WidthOfImage/2),position_y.word.o+(HeightOfImage/2));
			}
		}
		if(word_level_1[WordRandom[Index]][0]=='D'&&word_level_1[WordRandom[Index]][1]=='E'&&word_level_1[WordRandom[Index]][2]=='N'&&word_level_1[WordRandom[Index]][3]=='Y'){
			if(arr[0]=='D'&&arr[1]=='E'||arr[1]=='D'&&arr[2]=='E'||arr[2]=='D'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='D'||arr[1]=='E'&&arr[2]=='D'||arr[2]=='E'&&arr[3]=='D'){
					iFilledCircle(position_x.deny.d+(WidthOfImage/2),position_y.deny.d+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.deny.e+(WidthOfImage/2),position_y.deny.e+(WidthOfImage/2),3,6);
					iLine(position_x.deny.d+(WidthOfImage/2),position_y.deny.d+(HeightOfImage/2),position_x.deny.e+(WidthOfImage/2),position_y.deny.e+(HeightOfImage/2));
			}
			if(arr[0]=='Y'&&arr[1]=='D'||arr[1]=='Y'&&arr[2]=='D'||arr[2]=='Y'&&arr[3]=='D'||arr[0]=='D'&&arr[1]=='Y'||arr[1]=='D'&&arr[2]=='Y'||arr[2]=='D'&&arr[3]=='Y'){
					iFilledCircle(position_x.deny.d+(WidthOfImage/2),position_y.deny.d+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.deny.y+(WidthOfImage/2),position_y.deny.y+(WidthOfImage/2),3,6);
					iLine(position_x.deny.d+(WidthOfImage/2),position_y.deny.d+(HeightOfImage/2),position_x.deny.y+(WidthOfImage/2),position_y.deny.y+(HeightOfImage/2));
			}
			if(arr[0]=='D'&&arr[1]=='N'||arr[1]=='D'&&arr[2]=='N'||arr[2]=='D'&&arr[3]=='N'||arr[0]=='N'&&arr[1]=='D'||arr[1]=='N'&&arr[2]=='D'||arr[2]=='N'&&arr[3]=='D'){
					iFilledCircle(position_x.deny.d+(WidthOfImage/2),position_y.deny.d+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.deny.n+(WidthOfImage/2),position_y.deny.n+(WidthOfImage/2),3,6);
					iLine(position_x.deny.d+(WidthOfImage/2),position_y.deny.d+(HeightOfImage/2),position_x.deny.n+(WidthOfImage/2),position_y.deny.n+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='E'||arr[1]=='N'&&arr[2]=='E'||arr[2]=='N'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='N'||arr[1]=='E'&&arr[2]=='N'||arr[2]=='E'&&arr[3]=='N'){
					iFilledCircle(position_x.deny.e+(WidthOfImage/2),position_y.deny.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.deny.n+(WidthOfImage/2),position_y.deny.n+(WidthOfImage/2),3,6);
					iLine(position_x.deny.e+(WidthOfImage/2),position_y.deny.e+(HeightOfImage/2),position_x.deny.n+(WidthOfImage/2),position_y.deny.n+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='Y'||arr[1]=='N'&&arr[2]=='Y'||arr[2]=='N'&&arr[3]=='Y'||arr[0]=='Y'&&arr[1]=='N'||arr[1]=='Y'&&arr[2]=='N'||arr[2]=='Y'&&arr[3]=='N'){
					iFilledCircle(position_x.deny.y+(WidthOfImage/2),position_y.deny.y+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.deny.n+(WidthOfImage/2),position_y.deny.n+(WidthOfImage/2),3,6);
					iLine(position_x.deny.y+(WidthOfImage/2),position_y.deny.y+(HeightOfImage/2),position_x.deny.n+(WidthOfImage/2),position_y.deny.n+(HeightOfImage/2));
			}
			if(arr[0]=='Y'&&arr[1]=='E'||arr[1]=='Y'&&arr[2]=='E'||arr[2]=='Y'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='Y'||arr[1]=='E'&&arr[2]=='Y'||arr[2]=='E'&&arr[3]=='Y'){
					iFilledCircle(position_x.deny.y+(WidthOfImage/2),position_y.deny.y+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.deny.e+(WidthOfImage/2),position_y.deny.e+(WidthOfImage/2),3,6);
					iLine(position_x.deny.y+(WidthOfImage/2),position_y.deny.y+(HeightOfImage/2),position_x.deny.e+(WidthOfImage/2),position_y.deny.e+(HeightOfImage/2));
			}
		}
		if(word_level_1[WordRandom[Index]][0]=='G'&&word_level_1[WordRandom[Index]][1]=='O'&&word_level_1[WordRandom[Index]][2]=='N'&&word_level_1[WordRandom[Index]][3]=='E'){
			if(arr[0]=='G'&&arr[1]=='O'||arr[1]=='G'&&arr[2]=='O'||arr[2]=='G'&&arr[3]=='O'||arr[0]=='O'&&arr[1]=='G'||arr[1]=='O'&&arr[2]=='G'||arr[2]=='O'&&arr[3]=='G'){
					iFilledCircle(position_x.gone.g+(WidthOfImage/2),position_y.gone.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.gone.o+(WidthOfImage/2),position_y.gone.o+(WidthOfImage/2),3,6);
					iLine(position_x.gone.g+(WidthOfImage/2),position_y.gone.g+(HeightOfImage/2),position_x.gone.o+(WidthOfImage/2),position_y.gone.o+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='G'||arr[1]=='E'&&arr[2]=='G'||arr[2]=='E'&&arr[3]=='G'||arr[0]=='G'&&arr[1]=='E'||arr[1]=='G'&&arr[2]=='E'||arr[2]=='G'&&arr[3]=='E'){
					iFilledCircle(position_x.gone.g+(WidthOfImage/2),position_y.gone.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.gone.e+(WidthOfImage/2),position_y.gone.e+(WidthOfImage/2),3,6);
					iLine(position_x.gone.g+(WidthOfImage/2),position_y.gone.g+(HeightOfImage/2),position_x.gone.e+(WidthOfImage/2),position_y.gone.e+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='N'||arr[1]=='G'&&arr[2]=='N'||arr[2]=='G'&&arr[3]=='N'||arr[0]=='N'&&arr[1]=='G'||arr[1]=='N'&&arr[2]=='G'||arr[2]=='N'&&arr[3]=='G'){
					iFilledCircle(position_x.gone.g+(WidthOfImage/2),position_y.gone.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.gone.n+(WidthOfImage/2),position_y.gone.n+(WidthOfImage/2),3,6);
					iLine(position_x.gone.g+(WidthOfImage/2),position_y.gone.g+(HeightOfImage/2),position_x.gone.n+(WidthOfImage/2),position_y.gone.n+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='O'||arr[1]=='N'&&arr[2]=='O'||arr[2]=='N'&&arr[3]=='O'||arr[0]=='O'&&arr[1]=='N'||arr[1]=='O'&&arr[2]=='N'||arr[2]=='O'&&arr[3]=='N'){
					iFilledCircle(position_x.gone.o+(WidthOfImage/2),position_y.gone.o+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.gone.n+(WidthOfImage/2),position_y.gone.n+(WidthOfImage/2),3,6);
					iLine(position_x.gone.o+(WidthOfImage/2),position_y.gone.o+(HeightOfImage/2),position_x.gone.n+(WidthOfImage/2),position_y.gone.n+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='E'||arr[1]=='N'&&arr[2]=='E'||arr[2]=='N'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='N'||arr[1]=='E'&&arr[2]=='N'||arr[2]=='E'&&arr[3]=='N'){
					iFilledCircle(position_x.gone.e+(WidthOfImage/2),position_y.gone.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.gone.n+(WidthOfImage/2),position_y.gone.n+(WidthOfImage/2),3,6);
					iLine(position_x.gone.e+(WidthOfImage/2),position_y.gone.e+(HeightOfImage/2),position_x.gone.n+(WidthOfImage/2),position_y.gone.n+(HeightOfImage/2));
			}
			if(arr[0]=='O'&&arr[1]=='E'||arr[1]=='O'&&arr[2]=='E'||arr[2]=='O'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='O'||arr[1]=='E'&&arr[2]=='O'||arr[2]=='E'&&arr[3]=='O'){
					iFilledCircle(position_x.gone.o+(WidthOfImage/2),position_y.gone.o+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.gone.e+(WidthOfImage/2),position_y.gone.e+(WidthOfImage/2),3,6);
					iLine(position_x.gone.o+(WidthOfImage/2),position_y.gone.o+(HeightOfImage/2),position_x.gone.e+(WidthOfImage/2),position_y.gone.e+(HeightOfImage/2));
			}
		}
		if(word_level_1[WordRandom[Index]][0]=='N'&&word_level_1[WordRandom[Index]][1]=='E'&&word_level_1[WordRandom[Index]][2]=='A'&&word_level_1[WordRandom[Index]][3]=='R'){
			if(arr[0]=='A'&&arr[1]=='E'||arr[1]=='A'&&arr[2]=='E'||arr[2]=='A'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='A'||arr[1]=='E'&&arr[2]=='A'||arr[2]=='E'&&arr[3]=='A'){
					iFilledCircle(position_x.earn.e+(WidthOfImage/2),position_y.earn.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.earn.a+(WidthOfImage/2),position_y.earn.a+(WidthOfImage/2),3,6);
					iLine(position_x.earn.e+(WidthOfImage/2),position_y.earn.e+(HeightOfImage/2),position_x.earn.a+(WidthOfImage/2),position_y.earn.a+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='N'||arr[1]=='E'&&arr[2]=='N'||arr[2]=='E'&&arr[3]=='N'||arr[0]=='N'&&arr[1]=='E'||arr[1]=='N'&&arr[2]=='E'||arr[2]=='N'&&arr[3]=='E'){
					iFilledCircle(position_x.earn.n+(WidthOfImage/2),position_y.earn.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.earn.e+(WidthOfImage/2),position_y.earn.e+(WidthOfImage/2),3,6);
					iLine(position_x.earn.n+(WidthOfImage/2),position_y.earn.n+(HeightOfImage/2),position_x.earn.e+(WidthOfImage/2),position_y.earn.e+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='R'||arr[1]=='E'&&arr[2]=='R'||arr[2]=='E'&&arr[3]=='R'||arr[0]=='R'&&arr[1]=='E'||arr[1]=='R'&&arr[2]=='E'||arr[2]=='R'&&arr[3]=='E'){
					iFilledCircle(position_x.earn.e+(WidthOfImage/2),position_y.earn.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.earn.r+(WidthOfImage/2),position_y.earn.r+(WidthOfImage/2),3,6);
					iLine(position_x.earn.e+(WidthOfImage/2),position_y.earn.e+(HeightOfImage/2),position_x.earn.r+(WidthOfImage/2),position_y.earn.r+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='A'||arr[1]=='R'&&arr[2]=='A'||arr[2]=='R'&&arr[3]=='A'||arr[0]=='A'&&arr[1]=='R'||arr[1]=='A'&&arr[2]=='R'||arr[2]=='A'&&arr[3]=='R'){
					iFilledCircle(position_x.earn.a+(WidthOfImage/2),position_y.earn.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.earn.r+(WidthOfImage/2),position_y.earn.r+(WidthOfImage/2),3,6);
					iLine(position_x.earn.a+(WidthOfImage/2),position_y.earn.a+(HeightOfImage/2),position_x.earn.r+(WidthOfImage/2),position_y.earn.r+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='R'||arr[1]=='N'&&arr[2]=='R'||arr[2]=='N'&&arr[3]=='R'||arr[0]=='R'&&arr[1]=='N'||arr[1]=='R'&&arr[2]=='N'||arr[2]=='R'&&arr[3]=='N'){
					iFilledCircle(position_x.earn.r+(WidthOfImage/2),position_y.earn.r+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.earn.n+(WidthOfImage/2),position_y.earn.n+(WidthOfImage/2),3,6);
					iLine(position_x.earn.r+(WidthOfImage/2),position_y.earn.r+(HeightOfImage/2),position_x.earn.n+(WidthOfImage/2),position_y.earn.n+(HeightOfImage/2));
			}
			if(arr[0]=='A'&&arr[1]=='N'||arr[1]=='A'&&arr[2]=='N'||arr[2]=='A'&&arr[3]=='N'||arr[0]=='N'&&arr[1]=='A'||arr[1]=='N'&&arr[2]=='A'||arr[2]=='N'&&arr[3]=='A'){
					iFilledCircle(position_x.earn.a+(WidthOfImage/2),position_y.earn.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.earn.n+(WidthOfImage/2),position_y.earn.n+(WidthOfImage/2),3,6);
					iLine(position_x.earn.a+(WidthOfImage/2),position_y.earn.a+(HeightOfImage/2),position_x.earn.n+(WidthOfImage/2),position_y.earn.n+(HeightOfImage/2));
			}
		}
		if(word_level_1[WordRandom[Index]][0]=='H'&&word_level_1[WordRandom[Index]][1]=='E'&&word_level_1[WordRandom[Index]][2]=='A'&&word_level_1[WordRandom[Index]][3]=='T'){
			if(arr[0]=='A'&&arr[1]=='E'||arr[1]=='A'&&arr[2]=='E'||arr[2]=='A'&&arr[3]=='E'||arr[0]=='E'&&arr[1]=='A'||arr[1]=='E'&&arr[2]=='A'||arr[2]=='E'&&arr[3]=='A'){
					iFilledCircle(position_x.heat.e+(WidthOfImage/2),position_y.heat.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.heat.a+(WidthOfImage/2),position_y.heat.a+(WidthOfImage/2),3,6);
					iLine(position_x.heat.e+(WidthOfImage/2),position_y.heat.e+(HeightOfImage/2),position_x.heat.a+(WidthOfImage/2),position_y.heat.a+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='T'||arr[1]=='E'&&arr[2]=='T'||arr[2]=='E'&&arr[3]=='T'||arr[0]=='T'&&arr[1]=='E'||arr[1]=='T'&&arr[2]=='E'||arr[2]=='T'&&arr[3]=='E'){
					iFilledCircle(position_x.heat.t+(WidthOfImage/2),position_y.heat.t+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.heat.e+(WidthOfImage/2),position_y.heat.e+(WidthOfImage/2),3,6);
					iLine(position_x.heat.t+(WidthOfImage/2),position_y.heat.t+(HeightOfImage/2),position_x.heat.e+(WidthOfImage/2),position_y.heat.e+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='H'||arr[1]=='E'&&arr[2]=='H'||arr[2]=='E'&&arr[3]=='H'||arr[0]=='H'&&arr[1]=='E'||arr[1]=='H'&&arr[2]=='E'||arr[2]=='H'&&arr[3]=='E'){
					iFilledCircle(position_x.heat.e+(WidthOfImage/2),position_y.heat.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.heat.h+(WidthOfImage/2),position_y.heat.h+(WidthOfImage/2),3,6);
					iLine(position_x.heat.e+(WidthOfImage/2),position_y.heat.e+(HeightOfImage/2),position_x.heat.h+(WidthOfImage/2),position_y.heat.h+(HeightOfImage/2));
			}
			if(arr[0]=='H'&&arr[1]=='A'||arr[1]=='H'&&arr[2]=='A'||arr[2]=='H'&&arr[3]=='A'||arr[0]=='A'&&arr[1]=='H'||arr[1]=='A'&&arr[2]=='H'||arr[2]=='A'&&arr[3]=='H'){
					iFilledCircle(position_x.heat.a+(WidthOfImage/2),position_y.heat.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.heat.h+(WidthOfImage/2),position_y.heat.h+(WidthOfImage/2),3,6);
					iLine(position_x.heat.a+(WidthOfImage/2),position_y.heat.a+(HeightOfImage/2),position_x.heat.h+(WidthOfImage/2),position_y.heat.h+(HeightOfImage/2));
			}
			if(arr[0]=='T'&&arr[1]=='H'||arr[1]=='T'&&arr[2]=='H'||arr[2]=='T'&&arr[3]=='H'||arr[0]=='H'&&arr[1]=='T'||arr[1]=='H'&&arr[2]=='T'||arr[2]=='H'&&arr[3]=='T'){
					iFilledCircle(position_x.heat.h+(WidthOfImage/2),position_y.heat.h+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.heat.t+(WidthOfImage/2),position_y.heat.t+(WidthOfImage/2),3,6);
					iLine(position_x.heat.h+(WidthOfImage/2),position_y.heat.h+(HeightOfImage/2),position_x.heat.t+(WidthOfImage/2),position_y.heat.t+(HeightOfImage/2));
			}
			if(arr[0]=='A'&&arr[1]=='T'||arr[1]=='A'&&arr[2]=='T'||arr[2]=='A'&&arr[3]=='T'||arr[0]=='T'&&arr[1]=='A'||arr[1]=='T'&&arr[2]=='A'||arr[2]=='T'&&arr[3]=='A'){
					iFilledCircle(position_x.heat.a+(WidthOfImage/2),position_y.heat.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.heat.t+(WidthOfImage/2),position_y.heat.t+(WidthOfImage/2),3,6);
					iLine(position_x.heat.a+(WidthOfImage/2),position_y.heat.a+(HeightOfImage/2),position_x.heat.t+(WidthOfImage/2),position_y.heat.t+(HeightOfImage/2));
			}
		}
	}
	if(level==2){
		if(word_level_2[WordRandom[Index]][0]=='D'&&word_level_2[WordRandom[Index]][1]=='R'&&word_level_2[WordRandom[Index]][2]=='E'&&word_level_2[WordRandom[Index]][3]=='A'&&word_level_2[WordRandom[Index]][4]=='M'){
			if(arr[0]=='A'&&arr[1]=='E'||arr[1]=='A'&&arr[2]=='E'||arr[2]=='A'&&arr[3]=='E'||arr[3]=='A'&&arr[4]=='E'||arr[0]=='E'&&arr[1]=='A'||arr[1]=='E'&&arr[2]=='A'||arr[2]=='E'&&arr[3]=='A'||arr[3]=='E'&&arr[4]=='A'){
					iFilledCircle(position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(WidthOfImage/2),3,6);
					iLine(position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(HeightOfImage/2),position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='R'||arr[1]=='E'&&arr[2]=='R'||arr[2]=='E'&&arr[3]=='R'||arr[3]=='E'&&arr[4]=='R'||arr[0]=='R'&&arr[1]=='E'||arr[1]=='R'&&arr[2]=='E'||arr[2]=='R'&&arr[3]=='E'||arr[3]=='R'&&arr[4]=='E'){
					iFilledCircle(position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(WidthOfImage/2),3,6);
					iLine(position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(HeightOfImage/2),position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(HeightOfImage/2));
			}
			if(arr[0]=='E'&&arr[1]=='D'||arr[1]=='E'&&arr[2]=='D'||arr[2]=='E'&&arr[3]=='D'||arr[3]=='E'&&arr[4]=='D'||arr[0]=='D'&&arr[1]=='E'||arr[1]=='D'&&arr[2]=='E'||arr[2]=='D'&&arr[3]=='E'||arr[3]=='D'&&arr[4]=='E'){
					iFilledCircle(position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(WidthOfImage/2),3,6);
					iLine(position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(HeightOfImage/2),position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(HeightOfImage/2));
			}
			if(arr[0]=='D'&&arr[1]=='A'||arr[1]=='D'&&arr[2]=='A'||arr[2]=='D'&&arr[3]=='A'||arr[3]=='D'&&arr[4]=='A'||arr[0]=='A'&&arr[1]=='D'||arr[1]=='A'&&arr[2]=='D'||arr[2]=='A'&&arr[3]=='D'||arr[3]=='A'&&arr[4]=='D'){
					iFilledCircle(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(WidthOfImage/2),3,6);
					iLine(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(HeightOfImage/2),position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='D'||arr[1]=='R'&&arr[2]=='D'||arr[2]=='R'&&arr[3]=='D'||arr[3]=='R'&&arr[4]=='D'||arr[0]=='D'&&arr[1]=='R'||arr[1]=='D'&&arr[2]=='R'||arr[2]=='D'&&arr[3]=='R'||arr[3]=='D'&&arr[4]=='R'){
					iFilledCircle(position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(WidthOfImage/2),3,6);
					iLine(position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(HeightOfImage/2),position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(HeightOfImage/2));
			}
			if(arr[0]=='A'&&arr[1]=='R'||arr[1]=='A'&&arr[2]=='R'||arr[2]=='A'&&arr[3]=='R'||arr[3]=='A'&&arr[4]=='R'||arr[0]=='R'&&arr[1]=='A'||arr[1]=='R'&&arr[2]=='A'||arr[2]=='R'&&arr[3]=='A'||arr[3]=='R'&&arr[4]=='A'){
					iFilledCircle(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(WidthOfImage/2),3,6);
					iLine(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(HeightOfImage/2),position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(HeightOfImage/2));
			}
			if(arr[0]=='M'&&arr[1]=='D'||arr[1]=='M'&&arr[2]=='D'||arr[2]=='M'&&arr[3]=='D'||arr[3]=='M'&&arr[4]=='D'||arr[0]=='D'&&arr[1]=='M'||arr[1]=='D'&&arr[2]=='M'||arr[2]=='D'&&arr[3]=='M'||arr[3]=='D'&&arr[4]=='M'){
					iFilledCircle(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(WidthOfImage/2),3,6);
					iLine(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(HeightOfImage/2),position_x.dream.d+(WidthOfImage/2),position_y.dream.d+(HeightOfImage/2));
			}
			if(arr[0]=='M'&&arr[1]=='A'||arr[1]=='M'&&arr[2]=='A'||arr[2]=='M'&&arr[3]=='A'||arr[3]=='M'&&arr[4]=='A'||arr[0]=='A'&&arr[1]=='M'||arr[1]=='A'&&arr[2]=='M'||arr[2]=='A'&&arr[3]=='M'||arr[3]=='A'&&arr[4]=='M'){
					iFilledCircle(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(WidthOfImage/2),3,6);
					iLine(position_x.dream.a+(WidthOfImage/2),position_y.dream.a+(HeightOfImage/2),position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='M'||arr[1]=='R'&&arr[2]=='M'||arr[2]=='R'&&arr[3]=='M'||arr[3]=='R'&&arr[4]=='M'||arr[0]=='M'&&arr[1]=='R'||arr[1]=='M'&&arr[2]=='R'||arr[2]=='M'&&arr[3]=='R'||arr[3]=='M'&&arr[4]=='R'){
					iFilledCircle(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(WidthOfImage/2),3,6);
					iLine(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(HeightOfImage/2),position_x.dream.r+(WidthOfImage/2),position_y.dream.r+(HeightOfImage/2));
			}
			if(arr[0]=='M'&&arr[1]=='E'||arr[1]=='M'&&arr[2]=='E'||arr[2]=='M'&&arr[3]=='E'||arr[3]=='M'&&arr[4]=='E'||arr[0]=='E'&&arr[1]=='M'||arr[1]=='E'&&arr[2]=='M'||arr[2]=='E'&&arr[3]=='M'||arr[3]=='E'&&arr[4]=='M'){
					iFilledCircle(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(WidthOfImage/2),3,6);
					iLine(position_x.dream.m+(WidthOfImage/2),position_y.dream.m+(HeightOfImage/2),position_x.dream.e+(WidthOfImage/2),position_y.dream.e+(HeightOfImage/2));
			}
		}
		if(word_level_2[WordRandom[Index]][0]=='S'&&word_level_2[WordRandom[Index]][1]=='W'&&word_level_2[WordRandom[Index]][2]=='I'&&word_level_2[WordRandom[Index]][3]=='N'&&word_level_2[WordRandom[Index]][4]=='G'){
			if(arr[0]=='N'&&arr[1]=='I'||arr[1]=='N'&&arr[2]=='I'||arr[2]=='N'&&arr[3]=='I'||arr[3]=='N'&&arr[4]=='I'||arr[0]=='I'&&arr[1]=='N'||arr[1]=='I'&&arr[2]=='N'||arr[2]=='I'&&arr[3]=='N'||arr[3]=='I'&&arr[4]=='N'){
					iFilledCircle(position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(WidthOfImage/2),3,6);
					iLine(position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(HeightOfImage/2),position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(HeightOfImage/2));
			}
			if(arr[0]=='I'&&arr[1]=='W'||arr[1]=='I'&&arr[2]=='W'||arr[2]=='I'&&arr[3]=='W'||arr[3]=='I'&&arr[4]=='W'||arr[0]=='W'&&arr[1]=='I'||arr[1]=='W'&&arr[2]=='I'||arr[2]=='W'&&arr[3]=='I'||arr[3]=='W'&&arr[4]=='I'){
					iFilledCircle(position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(WidthOfImage/2),3,6);
					iLine(position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(HeightOfImage/2),position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(HeightOfImage/2));
			}
			if(arr[0]=='I'&&arr[1]=='S'||arr[1]=='I'&&arr[2]=='S'||arr[2]=='I'&&arr[3]=='S'||arr[3]=='I'&&arr[4]=='S'||arr[0]=='S'&&arr[1]=='I'||arr[1]=='S'&&arr[2]=='I'||arr[2]=='S'&&arr[3]=='I'||arr[3]=='S'&&arr[4]=='I'){
					iFilledCircle(position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(WidthOfImage/2),3,6);
					iLine(position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(HeightOfImage/2),position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(HeightOfImage/2));
			}
			if(arr[0]=='S'&&arr[1]=='N'||arr[1]=='S'&&arr[2]=='N'||arr[2]=='S'&&arr[3]=='N'||arr[3]=='S'&&arr[4]=='N'||arr[0]=='N'&&arr[1]=='S'||arr[1]=='N'&&arr[2]=='S'||arr[2]=='N'&&arr[3]=='S'||arr[3]=='N'&&arr[4]=='S'){
					iFilledCircle(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(WidthOfImage/2),3,6);
					iLine(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(HeightOfImage/2),position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(HeightOfImage/2));
			}
			if(arr[0]=='W'&&arr[1]=='S'||arr[1]=='W'&&arr[2]=='S'||arr[2]=='W'&&arr[3]=='S'||arr[3]=='W'&&arr[4]=='S'||arr[0]=='S'&&arr[1]=='W'||arr[1]=='S'&&arr[2]=='W'||arr[2]=='S'&&arr[3]=='W'||arr[3]=='S'&&arr[4]=='W'){
					iFilledCircle(position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(WidthOfImage/2),3,6);
					iLine(position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(HeightOfImage/2),position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='W'||arr[1]=='N'&&arr[2]=='W'||arr[2]=='N'&&arr[3]=='W'||arr[3]=='N'&&arr[4]=='W'||arr[0]=='W'&&arr[1]=='N'||arr[1]=='W'&&arr[2]=='N'||arr[2]=='W'&&arr[3]=='N'||arr[3]=='W'&&arr[4]=='N'){
					iFilledCircle(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(WidthOfImage/2),3,6);
					iLine(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(HeightOfImage/2),position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='S'||arr[1]=='G'&&arr[2]=='S'||arr[2]=='G'&&arr[3]=='S'||arr[3]=='G'&&arr[4]=='S'||arr[0]=='S'&&arr[1]=='G'||arr[1]=='S'&&arr[2]=='G'||arr[2]=='S'&&arr[3]=='G'||arr[3]=='S'&&arr[4]=='G'){
					iFilledCircle(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(WidthOfImage/2),3,6);
					iLine(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(HeightOfImage/2),position_x.swing.s+(WidthOfImage/2),position_y.swing.s+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='N'||arr[1]=='G'&&arr[2]=='N'||arr[2]=='G'&&arr[3]=='N'||arr[3]=='G'&&arr[4]=='N'||arr[0]=='N'&&arr[1]=='G'||arr[1]=='N'&&arr[2]=='G'||arr[2]=='N'&&arr[3]=='G'||arr[3]=='N'&&arr[4]=='G'){
					iFilledCircle(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(WidthOfImage/2),3,6);
					iLine(position_x.swing.n+(WidthOfImage/2),position_y.swing.n+(HeightOfImage/2),position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(HeightOfImage/2));
			}
			if(arr[0]=='W'&&arr[1]=='G'||arr[1]=='W'&&arr[2]=='G'||arr[2]=='W'&&arr[3]=='G'||arr[3]=='W'&&arr[4]=='G'||arr[0]=='G'&&arr[1]=='W'||arr[1]=='G'&&arr[2]=='W'||arr[2]=='G'&&arr[3]=='W'||arr[3]=='G'&&arr[4]=='W'){
					iFilledCircle(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(WidthOfImage/2),3,6);
					iLine(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(HeightOfImage/2),position_x.swing.w+(WidthOfImage/2),position_y.swing.w+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='I'||arr[1]=='G'&&arr[2]=='I'||arr[2]=='G'&&arr[3]=='I'||arr[3]=='G'&&arr[4]=='I'||arr[0]=='I'&&arr[1]=='G'||arr[1]=='I'&&arr[2]=='G'||arr[2]=='I'&&arr[3]=='G'||arr[3]=='I'&&arr[4]=='G'){
					iFilledCircle(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(WidthOfImage/2),3,6);
					iLine(position_x.swing.g+(WidthOfImage/2),position_y.swing.g+(HeightOfImage/2),position_x.swing.i+(WidthOfImage/2),position_y.swing.i+(HeightOfImage/2));
			}
		}
		if(word_level_2[WordRandom[Index]][0]=='W'&&word_level_2[WordRandom[Index]][1]=='R'&&word_level_2[WordRandom[Index]][2]=='O'&&word_level_2[WordRandom[Index]][3]=='N'&&word_level_2[WordRandom[Index]][4]=='G'){
			if(arr[0]=='N'&&arr[1]=='O'||arr[1]=='N'&&arr[2]=='O'||arr[2]=='N'&&arr[3]=='O'||arr[3]=='N'&&arr[4]=='O'||arr[0]=='O'&&arr[1]=='N'||arr[1]=='O'&&arr[2]=='N'||arr[2]=='O'&&arr[3]=='N'||arr[3]=='O'&&arr[4]=='N'){
					iFilledCircle(position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(HeightOfImage/2),position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(HeightOfImage/2));
			}
			if(arr[0]=='O'&&arr[1]=='R'||arr[1]=='O'&&arr[2]=='R'||arr[2]=='O'&&arr[3]=='R'||arr[3]=='O'&&arr[4]=='R'||arr[0]=='R'&&arr[1]=='O'||arr[1]=='R'&&arr[2]=='O'||arr[2]=='R'&&arr[3]=='O'||arr[3]=='R'&&arr[4]=='O'){
					iFilledCircle(position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(HeightOfImage/2),position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(HeightOfImage/2));
			}
			if(arr[0]=='O'&&arr[1]=='W'||arr[1]=='O'&&arr[2]=='W'||arr[2]=='O'&&arr[3]=='W'||arr[3]=='O'&&arr[4]=='W'||arr[0]=='W'&&arr[1]=='O'||arr[1]=='W'&&arr[2]=='O'||arr[2]=='W'&&arr[3]=='O'||arr[3]=='W'&&arr[4]=='O'){
					iFilledCircle(position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(HeightOfImage/2),position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(HeightOfImage/2));
			}
			if(arr[0]=='W'&&arr[1]=='N'||arr[1]=='W'&&arr[2]=='N'||arr[2]=='W'&&arr[3]=='N'||arr[3]=='W'&&arr[4]=='N'||arr[0]=='N'&&arr[1]=='W'||arr[1]=='N'&&arr[2]=='W'||arr[2]=='N'&&arr[3]=='W'||arr[3]=='N'&&arr[4]=='W'){
					iFilledCircle(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(HeightOfImage/2),position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(HeightOfImage/2));
			}
			if(arr[0]=='W'&&arr[1]=='R'||arr[1]=='W'&&arr[2]=='R'||arr[2]=='W'&&arr[3]=='R'||arr[3]=='W'&&arr[4]=='R'||arr[0]=='R'&&arr[1]=='W'||arr[1]=='R'&&arr[2]=='W'||arr[2]=='R'&&arr[3]=='W'||arr[3]=='R'&&arr[4]=='W'){
					iFilledCircle(position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(HeightOfImage/2),position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(HeightOfImage/2));
			}
			if(arr[0]=='N'&&arr[1]=='R'||arr[1]=='N'&&arr[2]=='R'||arr[2]=='N'&&arr[3]=='R'||arr[3]=='N'&&arr[4]=='R'||arr[0]=='R'&&arr[1]=='N'||arr[1]=='R'&&arr[2]=='N'||arr[2]=='R'&&arr[3]=='N'||arr[3]=='R'&&arr[4]=='N'){
					iFilledCircle(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(HeightOfImage/2),position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='W'||arr[1]=='G'&&arr[2]=='W'||arr[2]=='G'&&arr[3]=='W'||arr[3]=='G'&&arr[4]=='W'||arr[0]=='W'&&arr[1]=='G'||arr[1]=='W'&&arr[2]=='G'||arr[2]=='W'&&arr[3]=='G'||arr[3]=='W'&&arr[4]=='G'){
					iFilledCircle(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(HeightOfImage/2),position_x.wrong.w+(WidthOfImage/2),position_y.wrong.w+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='N'||arr[1]=='G'&&arr[2]=='N'||arr[2]=='G'&&arr[3]=='N'||arr[3]=='G'&&arr[4]=='N'||arr[0]=='N'&&arr[1]=='G'||arr[1]=='N'&&arr[2]=='G'||arr[2]=='N'&&arr[3]=='G'||arr[3]=='N'&&arr[4]=='G'){
					iFilledCircle(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.n+(WidthOfImage/2),position_y.wrong.n+(HeightOfImage/2),position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(HeightOfImage/2));
			}
			if(arr[0]=='R'&&arr[1]=='G'||arr[1]=='R'&&arr[2]=='G'||arr[2]=='R'&&arr[3]=='G'||arr[3]=='R'&&arr[4]=='G'||arr[0]=='G'&&arr[1]=='R'||arr[1]=='G'&&arr[2]=='R'||arr[2]=='G'&&arr[3]=='R'||arr[3]=='G'&&arr[4]=='R'){
					iFilledCircle(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(HeightOfImage/2),position_x.wrong.r+(WidthOfImage/2),position_y.wrong.r+(HeightOfImage/2));
			}
			if(arr[0]=='G'&&arr[1]=='O'||arr[1]=='G'&&arr[2]=='O'||arr[2]=='G'&&arr[3]=='O'||arr[3]=='G'&&arr[4]=='O'||arr[0]=='O'&&arr[1]=='G'||arr[1]=='O'&&arr[2]=='G'||arr[2]=='O'&&arr[3]=='G'||arr[3]=='O'&&arr[4]=='G'){
					iFilledCircle(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(WidthOfImage/2),3,6);
					iFilledCircle(position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(WidthOfImage/2),3,6);
					iLine(position_x.wrong.g+(WidthOfImage/2),position_y.wrong.g+(HeightOfImage/2),position_x.wrong.o+(WidthOfImage/2),position_y.wrong.o+(HeightOfImage/2));
			}
		}
	}
}